# Python par la pratique : partie 3 - NumPy

Ce notebook fournit des ressources pour la pratique de Python.

Pour chacune des méthodes, il vous faudra bien comprendre leur fonctionnement et vous pourrez vous documenter sur internet (docs officielles et forums).
N'hésitez pas à modifier les cellules pour tester d'autres configurations que celles données ici.

Si vous souhaitez connaitre les méthodes disponibles d'un objet particulier, utilisez la function ``dir(obj)``.

### Import

In [1]:
import numpy as np

### Création de Arrays

Les tableaux NumPy sont des objets de classe `NDArray`. Pour créer un tableau, **on ne crée pas** directement une instance de la classe `NDArray` mais on utilise la fonction `np.array` qui en est une interface.

Cette fonction prend un itérable en argument.

In [2]:
arr = np.array([])
arr.shape

(0,)

In [3]:
arr = np.array([1, 2])
arr.shape

(2,)

In [4]:
arr = np.array([[1, 2], [3, 4]])
arr.shape

(2, 2)

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr.shape

In [ ]:
# La fonction np.zeros crée un tableau avec uniquement des 0. Les dimensions du tableau sont spécifiée en argument de la fonction
arr = np.zeros((2, 3))
arr

In [ ]:
# Idem que np.zeros
arr = np.ones((2, 3))
arr

In [ ]:
# Crée une matrice identité
arr = np.eye(4)
arr

### Génération d'une séquence de nombres

NumPy implémente un grand nombre de routine permettant de créer des séquences de nombre, en particulier les fonctions 
* `np.arange` qui est l'équivalent de la fonction `range`
* `np.linspace`

In [5]:
np.arange(2, 5, .5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
np.linspace(2, 5, 6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

### Etat d'un objet Array

In [7]:
arr = np.array([[1, 2], [3, 4]])

# Affiche les dimensions du tableau
print(arr.shape)
print(len(arr))

# Affiche le nombre de dimensions du tableau
print(arr.ndim)

# Affiche le nombre total d'éléments
print(arr.size)

# Affiche le type des données
print(arr.dtype)

(2, 2)
2
2
4
int64


In [8]:
# Modifie le type des données
arr2 = arr.astype(float)
arr2

array([[1., 2.],
       [3., 4.]])

### Opérations mathématiques

Les opérations mathématiques de base s'adaptent aux tableaux NumPy.

Les opérations `+`, `-`, `/` et `*` se font élément par élément.

In [9]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [10]:
# Addition élément par élément
arr + arr

array([[2, 4],
       [6, 8]])

In [11]:
# Soustraction élément par élément
arr - arr

array([[0, 0],
       [0, 0]])

In [12]:
# Multiplication élément par élément
arr * arr

array([[ 1,  4],
       [ 9, 16]])

In [13]:
# Division élément par élément
arr / arr

array([[1., 1.],
       [1., 1.]])

Voir aussi les routines ``np.add``, ``np.substract``, ``np.divide`` et ``np.multiply``

In [14]:
np.exp(arr)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [15]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [16]:
np.sin(arr)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [17]:
np.cos(arr)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [18]:
np.log(arr)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

### Algèbre linéaire

Les opérations d'algèbre linéaire sont en partie implémentées dans le module ``numpy.linalg`` :
* produit matriciel et vectoriel
* décompositions de matrices
* valeurs propres, vecteurs propres
* normes
* etc.

voir https://numpy.org/doc/stable/reference/routines.linalg.html

In [19]:
# Produit matriciel entre deux Arrays. Le résultats est un tableau NumPy
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 1], [1, 1]])

# Via la méthode dot
arr1.dot(arr2)

# Via l'opérateur @
arr1@arr2

array([[3, 3],
       [7, 7]])

In [20]:
# Inverse d'une matrice
arr = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Comparaisons

In [21]:
# Comparaison de deux arrays, élément par élément
arr1 == arr2

array([[ True, False],
       [False, False]])

In [22]:
# Comparaison des éléments d'une array avec un scalaire
arr1 < 3

array([[ True,  True],
       [False, False]])

In [23]:
# Test d'égalité de deux arrays
print(np.array_equal(arr1, arr2))
print(np.array_equal(arr1, arr1))

False
True


### Opérations statistiques

Les opérations statistiques (min, max, moyennes, etc.) agissent à la fois sur l'ensemble des valeurs de l'objet mais aussi sur les lignes (en utilisant l'argument ``axis = 0``) et sur les colonnes (en utilisant ``axis = 1``).

Noter que ``axis = -1`` correspond à la dernière dimension de l'array

In [24]:
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1. 2.]
 [3. 4.]]
10.0
[4. 6.]
[3. 7.]


In [25]:
print(arr)
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

[[1. 2.]
 [3. 4.]]
1.0
[1. 2.]
[1. 3.]


In [26]:
print(arr)
print(arr.max())
print(arr.max(axis=0))
print(arr.max(axis=1))

[[1. 2.]
 [3. 4.]]
4.0
[3. 4.]
[2. 4.]


In [27]:
# Moyenne empirique
print(arr)
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

[[1. 2.]
 [3. 4.]]
2.5
[2. 3.]
[1.5 3.5]


In [28]:
# Médiane
print(arr)
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

[[1. 2.]
 [3. 4.]]
2.5
[2. 3.]
[1.5 3.5]


In [29]:
# Ecart-type
print(arr)
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

[[1. 2.]
 [3. 4.]]
1.118033988749895
[1. 1.]
[0.5 0.5]


### Tri

La méthode `sort` permet de trier l'ensemble du tableau, selon les différents axes. L'opération se fait `inplace`, c'est à dire en modifiant directement les valeurs du tableau.
Inversement, la fonction `np.sort` renvoie une copie triée du tableau passé en argument.

L'argument `axis` permet d'agir sur les lignes ou sur les colonnes.

In [30]:
arr = np.array([[1, -2], [4, 3]])
print(arr)

# tri inplace
arr.sort()
print(arr)

[[ 1 -2]
 [ 4  3]]
[[-2  1]
 [ 3  4]]


In [31]:
arr = np.array([[1, -2], [4, 3]])
print(arr)

# Renvoie une copie du tableau
print(np.sort(arr))

[[ 1 -2]
 [ 4  3]]
[[-2  1]
 [ 3  4]]


In [32]:
arr = np.array([[1, -2], [4, 3]])
print(arr)

# tri des colonnes
arr.sort(axis=0) 
print(arr)

[[ 1 -2]
 [ 4  3]]
[[ 1 -2]
 [ 4  3]]


### Indexing et slicing

L'indexing sur des tableaux NumPy se fait de façon similaire aux listes, c'est-à-dire via des index (ou positions).

La principale différence est que l'indexing se fait selon les différentes dimensions du tableau, indépendamment les unes des autres.

Par exemple, récupérer un élément d'une liste de liste nécessite d'extraire la ou les sous-listes en préalable:

```python
l = [[1, 2, 3],
     [4, 5, 6]]

print(l[0][1]) # affiche 2
```

Or pour un tableau NumPy, l'utilisation du caractère `,` permet d'indéxer sur les deux dimensions (ou plus) directement :

```python
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

print(arr[0, 1])
```

Le caractère `:` permet d'extraire toutes les lignes ou toutes les colonnes (dans le cas 2D).

Voir https://numpy.org/doc/stable/user/basics.indexing.html

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# Affiche une ligne, ou un sous-tableau si la dimension est > 2
arr[1]

array([4, 5, 6])

In [35]:
# Affiche une colonne
arr[:, 1]

array([2, 5, 8])

In [36]:
# Affiche un sous-tableau
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# Affiche une colonne et un sous-ensemble des lignes
arr[0:2, 1]

array([2, 5])

In [38]:
# Affiche un sous-tableau
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [39]:
# Affiche toutes les lignes et un sous-ensemble des colonnes
arr[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [40]:
# Affiche toutes les lignes et un sous-ensemble des colonnes
arr[:, 2:]

array([[3],
       [6],
       [9]])

In [41]:
# Spécifie les indexes des lignes/colonnes à extraire
indexes_1 = [0, 2, 0, 2]
indexes_2 = [0, 0, 2, 2]
arr[indexes_1, indexes_2]

array([1, 7, 3, 9])

In [42]:
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

In [43]:
indexes = np.where(arr > 3)
arr[indexes]

array([4, 5, 6, 7, 8, 9])

### Manipulation d'arrays

In [44]:
# Transposée
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# version 1
print(np.transpose(arr))

# version 2, via la property T
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
# Reshape
arr = np.arange(0, 10, 1)
print(arr)
print(arr.reshape((2, 5)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [46]:
# Applatir une Array
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
### Combiner deux arrays par ligne
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(np.concatenate((arr, arr), axis=0))
print(np.vstack((arr, arr)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
### Combiner deux arrays par colonnes
print(arr)
print(np.concatenate((arr, arr), axis=1))
print(np.hstack((arr, arr)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


### Simulation de nombres aléatoires

La simulation de nombres aléatoires se fait via le module ``numpy.random``

In [ ]:
# Simulation selon une loi Gaussienne
np.random.normal(loc=0, scale=1, size=10)

In [ ]:
np.random.normal(loc=0, scale=1, size=10).reshape((2, 5))

In [ ]:
mean = (0, 0)
cov = ((1, 0), (0, 100))
x1, x2 = np.random.multivariate_normal(mean, cov, 5000).T

In [ ]:
np.random.exponential(scale=1, size=10)